#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen http-in
    bind :80
    balance roundrobin
    server web-01 3.85.136.169:80 check
    server web-02 35.175.105.163:80 check
EOF

# Restart HAProxy
sudo service haproxy restart

# Print the configured servers
echo "Configured servers: [\"web-01\"]"


